version: '3.5'

services:
  potential-pancake:
   container_name: potential-pancake
   image: giovannipajeu/tech-challenge-73-potential-pancake:latest
   networks:
    - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped
   
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
