apiVersion: v1
kind: Pod
metadata:
  name: "tech-challenge-73"
  labels:
    app: "tech-challenge-73"
spec:
  containers:
    - name: tech-challenge-73
      image: acdmanderson/tech-challenge-73:0.0.2
      resources:
        limits:
          cpu: "0.5"
          memory: 500Mi
        requests:
          cpu: "0.2"
          memory: 200Mi
      ports:
        - containerPort: 9001
      env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DATABASE_URL
