apiVersion: v1
kind: Pod
metadata:
  name: "postgres-pod"
  labels:
    app: "postgres-pod"
spec:
  containers:
    - name: postgres-pod
      image: "postgres"
      resources:
        limits:
          cpu: "0.5"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 500Mi
      livenessProbe: 
        tcpSocket:
          port: 5432
        initialDelaySeconds: 5
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
  #     volumeMounts:
  #       - name: shared
  #         mountPath: /var/lib/postgresql/data
  # volumes:
  #   - name: shared
  #     persistentVolumeClaim:
  #       claimName: tech-challenge-73-pvc
