apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
spec:
  selector:
    app: postgres-pod
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: 32000