apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-tech-challenge-73
  namespace: default
  labels:
    app: deployment-tech-challenge-73
spec:
  selector:
    matchLabels:
      app: "tech-challenge-73"
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "tech-challenge-73"
    spec:
      containers:
        - name: "tech-challenge-73"
          image: acdmanderson/tech-challenge-73:0.0.2
          resources:
            limits:
              cpu: "0.5"
              memory: 500Mi
            requests:
              cpu: "0.2"
              memory: 200Mi
          livenessProbe:
            tcpSocket:
              port: 9001
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 9001
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_url
            - name: PGSSLMODE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: PGSSLMODE
        
