apiVersion: v1
kind: PersistentVolume
metadata:
  name: tech-challenge-73-pv
  namespace: default
  labels:
    app: tech-challenge-73-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-db
  persistentVolumeReclaimPolicy: Retain #delete and Recicle
  hostPath:
    path: /Users/andersoncostadamata/Documents/fiap/tech-challenge-73/k8s/data
