apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name:  potential-panckake
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  potential-panckake
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: Memory
      target:
        type: Utilization
        averageUtilization: 50
  