name: Deploy to Vercel
env:
  TOKEN: ${{secrets.TF_API_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID:}}
  AWS_SECRET_ACCESS_KEY: ${{secrets;AWS_SECRET_ACCESS_KEY:}}
on:
  push:
    branches:
      - build/dockerfile
    paths: ["src/**"]

jobs:

  Testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Do Código
        uses: actions/checkout@v3
      - name: Preparando Ambiente
        run: |
          sudo apt update -y
          sudo apt install nodejs -y
          sudo npm install
      - name: Fazendo testes
        run: npm run test
        
  IaC:
    runs-on: ubuntu-latest
    needs: Testes
    steps:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
        cli_config_credentials_token: $TOKEN
    -  name: Setup Aws Account
       aws-region: us-east-1
       aws_access_key_id: $AWS_ACCESS_KEY_ID
       aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
     - name: Terraform init
       working-directory: ./src
       run: terraform init 
     - name: Terraform Plan
       run: terraform plan 
     - name: Terraform Apply
       run: terraform apply -auto-approve
