name: Deploy to Vercel
env:
  TOKEN: ${{ secrets.TOKEN }}
on:
  push:
    branches:
      - build/dockerfile

jobs:

  Testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Do Código
        uses: actions/checkout@v3
      - name: Preparando Ambiente
        run: |
          sudo apt update -y
          sudo apt install nodejs -y
          sudo npm install
      - name: Fazendo testes
        run: npm run test
        
  IaC:
    runs-on: ubuntu-latest
    needs: Testes
    steps:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     - name: Terraform init
       run: terraform init 
     - name: Terraform Plan
       run: terraform plan -var-file=config/local/terraform.tfvars
     - name: Terraform Apply
       run: terraform apply -auto-approve
