name: Deploy to ?
on:
  push:
    branches:
      - build/dockerfile
   

jobs:

  Testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Do Código
        uses: actions/checkout@v3
      - name: Preparando Ambiente
        run: |
          sudo apt update -y
          sudo apt install nodejs -y
          sudo npm install
      - name: Fazendo testes
        run: npm run test

  Docker:
    needs: Testes
    runs-on: ubuntu-latest
    steps:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Log in to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Build and push Docker image
       uses: docker/build-push-action@v2
       with:
        file: Dockerfile
        push: true
        tags: |
            giovannipajeu/tech-challenge-73-potential-pancake:latest 
            giovannipajeu/tech-challenge-73-potential-pancake:${{github.run_number}}      
  Deploy:
    needs: Docker
    runs-on: ubuntu-latest
    steps:
     - name: Connect And Run Docker
       run: |
         echo '${{secrets.SSH}}' > ssh.key
         sudo chmod 400 ssh.key
         ssh-keyscan -H 168.138.154.17 >> ~/.ssh/known_hosts
         ssh -i ssh.key opc@168.138.154.17
         docker-compose up -d

