name: Deploy to Vercel
env:
  TOKEN: ${{ secrets.TOKEN }}
on:
  push:
    branches:
      - build/docekrfile

jobs:

  Testes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Do Código
        uses: actions/checkout@v3
      - name: Preparando Ambiente
        run: |
          apt update -y
          apt install nodejs -y
          npm install
      - name: Fazendo testes
        run: npm run test
        
  IaC:
    runs-on: ubuntu-latest
    needs: Testes
    steps:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     - name: Terraform init
       run: terraform init 
     - name: Terraform Apply
       run: terraform apply -auto-approve

  # Build:
  #   runs-on: ubuntu-latest
  #   needs: Iac
  #   steps:
  #     - name: Checkout do código
  #       uses: actions/checkout@v3
  #     - name: Build Docker Image
  #       run: 
  # Deploy:
  #  runs-on: ubuntu-latest
  #  needs: Build
  #  steps:
  #   - name: Pull Registry
  #     run:
  #   - name: Push to EKS
  #     run:      